ci(emu): dirty fix for kunminghu-v2 & bump action version (#5791)
Fix this (hopefully):

```
  warning: 9114012def7a730a5e9d334e5122d800825dca11:.gitmodules, multiple configurations found for 'submodule.riscv-rocket.url'. Skipping second one!
  warning: 9114012def7a730a5e9d334e5122d800825dca11:.gitmodules, multiple configurations found for 'submodule.uncore.path'. Skipping second one!
  warning: 9114012def7a730a5e9d334e5122d800825dca11:.gitmodules, multiple configurations found for 'submodule.uncore.url'. Skipping second one!
  warning: 9114012def7a730a5e9d334e5122d800825dca11:.gitmodules, multiple configurations found for 'submodule.dramsim2.path'. Skipping second one!
  warning: 9114012def7a730a5e9d334e5122d800825dca11:.gitmodules, multiple configurations found for 'submodule.dramsim2.url'. Skipping second one!
  Fetching submodule hardfloat
  Error: fatal: remote error: upload-pack: not our ref 1c8a6e6815eadebc1592c65e10a2ba87ecabb3c6
  Errors during submodule fetch:
  	hardfloat
  Error: fatal: Fetched in submodule path 'rocket-chip', but it did not contain 46f1efefa1ff431bffe3262e4830bc50316842f4. Direct fetching of that commit failed.
  Error: The process '/usr/bin/git' failed with exit code 128
```

1. Drop `submodules: true` in `actions/checkout`, let `make init-force`
do this.
2. If `make init-force` failed, assume it's caused by this 'not our ref'
and try fixing by running `git fetch --unshallow` in `rocket-chip` and
retry `make init-force`.

Also:
- bump action versions, as node20 is deprecated.
- relax timeout of `artifacts-uploading` to 60min.

**NOTE: Do not pick this to kunminghu-v3**

---------

Signed-off-by: ngc7331 <ngc7331@outlook.com>